CREATE TABLE car (
id SERIAL PRIMARY KEY,
brand VARCHAR (100) NOT NULL,
model VARCHAR (100) NOT NULL,
cost DECIMAL (10, 2) NOT NULL
);

CREATE TABLE people (
id SERIAL PRIMARY KEY,
name VARCHAR (100) NOT NULL,
age INTEGER NOT NULL,
license BOOL NOT NULL,
car_id INTEGER NOT NULL REFERENCES car (id)
);